<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.7" />
    <ProjectReference Include="..\Fcg.Contracts\Fcg.Contracts.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Common\Fcg.Payment.Common.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Domain\Fcg.Payment.Domain.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Infra\Fcg.Payment.Infra.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Proxy.Auth\Fcg.Payment.Proxy.Auth.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Proxy.Games\Fcg.Payment.Proxy.Games.csproj" />
    <ProjectReference Include="..\Fcg.Payment.Proxy.User\Fcg.Payment.Proxy.User.csproj" />
  </ItemGroup>

</Project>
